### ISSUE TITLE
array_merge of session data into $user['data'] can lead to an exception

### ISSUE THREAD

**Issue by tremby** [clowdy/laravel-raven#15]
At https://github.com/clowdy/laravel-raven/blob/master/src/Client.php#L98 you run `array_merge` putting some stuff into `$user['data']`.

This was failing for me just now -- complaining that `$user['data']` is a string rather than an array. After tracing it back, it turns out this is because I'm using the UserDataProcessor (which I wrote for the L4 branch, and still intend to port to L5, by the way), and this is replacing the context's `user` key with its own data structure, which may or may not include the `data` key, and even if it does that `data` key may or may not be an array. In this case there was a `data` key of type `string`. You can't run `array_merge` on a string.

At minimum in `Client` we should add a check to see if `data` is an array, but before I open a pull request, I wanted to touch base with you.

1. If the data contained in `$user` already has a `data` key (as in my case), this could be anything; not necessarily what the code here is expecting. Even if it's an array it might not make sense to add session data to it. As far as I can tell, the current code is just mimicing [the behaviour of the official Raven client](https://github.com/getsentry/raven-php/blob/master/lib/Raven/Client.php#L372). Is the `data` key handled specially in some way by Sentry, or could this key be anything?
2. Incidentally, while I'm in this chunk of code, I understand that not everybody would want to use `UserDataProcessor` and so it should not be enabled by default (having the package leak the array representation of the application's user model to Sentry without asking is not a good idea), but I wonder if by default passing at least the current user ID or lack thereof would be a good idea?

**Comment by pulkitjalan** [comment]
1. I'm not sure if the `data` key is handled in a special way by Sentry. That was done to simply mimic the official client with Laravel's sessions instead of php's.

2. Yea maybe passing just the user id would be ok.

I can certainly have a look if you submit a pr.

**Comment by tremby** [comment]
Presumably, then, you think it best to continue to mimic Raven's behaviour. In light of that, any thoughts on what to do in the case where a provider has already populated `$user['data']`, as in my original case above? The existing code merges session data into it if it's an array, and we could keep that even though it could be confusing in edge cases, but what about if it's not an array?

**Comment by pulkitjalan** [comment]
When user['data'] is not an array what does it look like in Sentry? Just wondering.

I would say it might be best to create an array and add session data under a different key. User['data']['original'] and user['data']['session'] or something.

If not then what about ignoring the session for certain cases?

**Comment by tremby** [comment]
Good question; I'll have to do some testing with this later and find out what happens with various different types, and deeper arrays. (The string which was being set was not actually useful to me; the main problem was that an exception was being thrown which meant we got no error reports at all for a while.)

Your suggestion to ignore the session data if 'data' is already set could also be valid: anyone using a processor like this obviously cares about what is being sent to Sentry, so if they particularly want the session data they'd notice and could add a new processor to restore it. Having said that, 'data' only suddenly started being set for me for particular users once that field in the database had a value in it, so the developer wouldn't necessarily notice right away that session data was missing.

I'll investigate what Sentry is doing.

**Comment by pulkitjalan** [comment]
Ok cool, interested in hearing what you find.

**Comment by pulkitjalan** [comment]
@tremby This has been removed in the latest version and you `UserDataProcessor` from version 1 has been migrated over. Should be working as expected now.

**Comment by tremby** [comment]
Fantastic, thanks. I haven't had a chance to use this in a while; hopefully I'm on another Laravel project soon and will report back.
