### ISSUE TITLE
Get context without sending error

### ISSUE THREAD

**Issue by tremby** [clowdy/laravel-raven#20]
Something I'd really like is to get as much configuration as possible from the error reporter without sending an actual error, and then use this data to configure the JS version of Raven. I'd want this to include the tags added by the processors I have configured (that's the two I wrote for this package, and sometimes others specific to projects).

This would mean I can configure Raven in just one place (in PHP) and don't have to reimplement the configuration in JS.

I don't know too much about Raven itself. Just wondering if you know of any simple method to do this off hand, or a good starting point where I could add the suitable functionality. If appropriate we could add a method (or even a view too) which configures the JS version of Raven.

**Comment by pulkitjalan** [comment]
hmm, maybe a function might be the best thing to do. I have not really used sentry in js so am not 100% sure what it would need.

I suppose the js dsn could go in the config, and the function could be used to retrieve it. Perhaps even a helper function for use directly in blade?

Thoughts?

**Comment by tremby** [comment]
Just want to comment to say this isn't forgotten. Just awaiting the next time I can charge a client for helping develop this. :)

**Comment by pulkitjalan** [comment]
This package is deprecated. Use https://github.com/twineis/raven-php instead. That is basically a copy with some bulk removed and with Lumen support. Ill eventually add the processors to that also.
