### ISSUE TITLE
Can't get it to be working

### ISSUE THREAD

**Issue by huglester** [clowdy/laravel-raven#23]
Hello,

I am using RabbitMQ package to make use of queues.
Email sending, Queued jobs work.

But this one raven - can't make it.

I have added the ServiceProvider, (did not add the alias)
Also did not publish the config.

I have added this env data:
```bash
RAVEN_DSN=http://.../9
RAVEN_QUEUE_CONNECTION=rabbitmq
RAVEN_QUEUE_NAME=default
```

The listener shows the Clowdy jobs been fired, I see some stats passing the rabbitmq, but I can't seem anything to appear on the sentry itself. It simply shows 'no errors'.

```bash
php artisan queue:listen --sleep=1                                                                                                                      
[2016-04-17 20:43:45] Processed: Clowdy\Raven\Job
[2016-04-17 20:43:45] Processed: Clowdy\Raven\Job
```

Any idea what I could have been missed?

Thank you

**Comment by pulkitjalan** [comment]
I've not used rabbitmq before so am unsure, are u able to see the job data?

**Comment by pulkitjalan** [comment]
Another thing to try might be to disable queues to make sure data is sent to sentry without queues.

**Comment by huglester** [comment]
I just tried changing the queue to beanstalkd, I see the job 'appears' in the beanstalk_console with some data, but after I run listener, the job is simply gone..
Probably it is something to do with my sentry server. 

I also tried RAVEN_QUEUE_CONNECTION=sync - same results

**Comment by pulkitjalan** [comment]
Try publishing the config

**Comment by huglester** [comment]
Hello, 

I am not sure what actually helped, but been playing around, and it started working.. But I think the main problem was that someone switched sentry from http to https... and URL was not updated
