### ISSUE TITLE
Setting user data

### ISSUE THREAD

**Issue by tremby** [clowdy/laravel-raven#6]
It might be a good idea to set user data automatically based on `Auth::user()`, or to provide an optional processor which does this.

I don't quite understand the recent change in Monolog at https://github.com/Seldaek/monolog/commit/c1fd9cddf2f2d4f49dc56cb647681ee086c6fca3 which makes `Raven::user_context()` useless -- it is wiped when a new message is being logged. (I commented on that commit just now.)

I don't want to pass in user data every time I run a `Log::error(...)` so I use a processor like this:

```php
'processors' => [
    // Current user status
    function ($record) {
        if ($user = Auth::user()) {
            $record['context']['user'] = $user->toArray();
        } else {
            $record['context']['user'] = ['id' => null];
        }
        return $record;
    },
],
```

I'm setting `['id' => null]` for a non-logged-in user because I think it's useful to see that rather than a lack of user data in an error report I can see categorically that a user was not logged in.

If there's a nicer way to set user context than this, given what I mentioned above, I'd like to hear it.

But in any case, please consider adding something like this.

**Comment by pulkitjalan** [comment]
I did add a method to pull some user data from the session in laravel: https://github.com/clowdy/laravel-raven/blob/master/src/Client.php#L86

The reason for not putting all the user data into the error was for security. The processor you suggested could be added as a suggestion in the config file though?

**Comment by tremby** [comment]
Sure. I could provide it as a processor class to optionally include?

**Comment by pulkitjalan** [comment]
Yea, sounds good to me.
