### ISSUE TITLE
Pass environment to sentry

### ISSUE THREAD

**Issue by tremby** [clowdy/laravel-raven#8]
It would be good to have a default tag being sent to Sentry for the current environment.

I'm setting it currently like this in the config file:

```php
'options' => [
    'tags' => [
        'environment' => App::environment(),
    ],
],
```

I think this would be a useful default, whether in the default config file or added automatically.

**Comment by pulkitjalan** [comment]
That is already defaulted: https://github.com/clowdy/laravel-raven/blob/master/src/Client.php#L35

**Comment by tremby** [comment]
That does not appear in the Sentry report for me.

**Comment by pulkitjalan** [comment]
Are you using L4 or L5?

**Comment by tremby** [comment]
L4 on the project I'm testing on right now. I'll be using it with L5 too.

Ah, found the problem. When I define other tags, the default one is removed. Perhaps you need an `array_merge_recursive` call in there somewhere.

**Comment by tremby** [comment]
Oh, you're not even merging it. It's a flat array, so no recursive necessary. Want a patch to merge the configured with the defaults, or did you decide to replace all default tags with configured ones on purpose?

**Comment by pulkitjalan** [comment]
Ah nice spot, changed the `array_merge` to `array_replace_recursive`, so should be fixed now.

**Comment by tremby** [comment]
Works for me. Thanks.
